version: "3.9"

services:
  app:
    image: satisfiestechgithubio-app:latest
    ports:
      - "9090:9090"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      SPRING_DATASOURCE_URL: url
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
